 server.port=8081


spring.servlet.multipart.enabled=true


# ???? ???? ????? ??????? (???? ????? ???? dev/prod)
file.upload-dir=uploads

# ??????? ??? (???????)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# swagger
springdoc.swagger-ui.path=/swagger-ui.html
# URL ????? ?? ?????? (??? ??????? ?? ???? ???? ????? ?? ?? ????? ??? ?????)
spring.datasource.url= jdbc:postgresql://localhost:5433/citus_db

# ??????? ? ?????? ?? ?? ????? ???? ????
spring.datasource.username=admin
spring.datasource.password=adminpass

# ?????? ??????
spring.datasource.driver-class-name=org.postgresql.Driver

# ??????? Hibernate ???? ???? ?????? ?????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.properties.hibernate.generate_statistics=false


spring.jpa.properties.hibernate.jdbc.batch_size=2000
spring.jpa.properties.hibernate.order_inserts=true


logging.file.name=app.
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web=DEBUG


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=2000ms
#spring:
#datasource:
# ?? localhost ?? ???? IP ????? ???? ??????? ????. ???? 5433 ???.
#url: jdbc:postgresql://localhost:5433/citus_db
#username: admin
#password: adminpass
#jpa:
#hibernate:
#ddl-auto: validate
#properties:
#hibernate:
#dialect: org.hibernate.dialect.PostgreSQLDialect
#transaction:
#default-timeout: 30

spring:
kafka:
bootstrap-servers: localhost:9094
producer:
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
consumer:
group-id: inventory-group
auto-offset-reset: earliest
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
properties:
spring.json.trusted.packages: "*"